# Generated by Django 5.1.2 on 2024-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, upload_to='items/images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(null=True, upload_to='items/images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(null=True, upload_to='items/images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(null=True, upload_to='items/images/'),
        ),
    ]
