# Generated by Django 5.1.2 on 2024-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
