# Generated by Django 5.1.2 on 2024-10-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cart_cartitem_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
