# Generated by Django 5.1.2 on 2024-11-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_itemimage_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
