# Generated by Django 5.1.2 on 2024-12-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='value',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='comment', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
