# Generated by Django 5.1.2 on 2024-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_review_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Ngaikam', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('leading', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('business plan', 'business plan'), ('not classified', 'not classified'), ('social media', 'social media'), ('advertisement', 'advertisement')], max_length=30)),
                ('cover', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('date_added', models.DateField()),
            ],
        ),
    ]
