# Generated by Django 5.1.2 on 2025-02-15 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_blogpost_date_added'),
        ('partner', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='partner.provider'),
        ),
    ]
