# Generated by Django 5.1.2 on 2025-03-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('food', 'food'), ('beauty', 'beauty'), ('decoration', 'decoration'), ('cloths', 'cloths'), ('elelctronics', 'elelctronics'), ('others', 'others')], default='others', max_length=50),
        ),
    ]
