# Generated by Django 5.1.2 on 2025-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_item_image1_alter_item_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('food', 'food'), ('beauty', 'beauty'), ('decoration', 'decoration'), ('cloths', 'cloths'), ('electronics', 'electronics'), ('others', 'others')], default='others', max_length=50),
        ),
    ]
