# Generated by Django 5.1.2 on 2025-04-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownload',
            fields=[
                ('sk', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
