# Generated by Django 5.1.2 on 2024-10-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='label',
            field=models.CharField(choices=[('company', 'company'), ('partners', 'partners')], default='company', max_length=30),
        ),
    ]
