# Generated by Django 5.1.2 on 2024-10-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_provider_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='country',
            new_name='city',
        ),
    ]
