# Generated by Django 5.1.2 on 2024-11-22 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_rename_country_provider_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecoveryCode',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.provider')),
            ],
        ),
    ]
