# Generated by Django 5.1.2 on 2025-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='page_slug',
            field=models.CharField(default=models.CharField(max_length=70), max_length=100),
        ),
    ]
