# Generated by Django 5.1.2 on 2025-05-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_provider_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='page_slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
